Add -I<include_dir> to support users that use #include <jasper/jasper.h>
jasper-software/jasper pull request #214
Opened 2020-03-06 18:17 UTC by jhgit

For example, GEGL (gegl.org) uses that style of include.

2020-07-28 18:55 UTC, MaxKellermann commented
Having both looks wrong to me, so I don't like this PR.
On the other hand, JasPer's own applications sometimes use `<jasper.h>` and others use `<jasper/jas_*.h>` - this is inconsistent!
... and to make it worse, `jasper.h` contains includes like `<jasper/jas_*.h>`, which cannot work with JasPer's pkg-config file... and only ever worked because the installation include path is a standard include path!
So, after all, this PR may be necessary to work around what looks like a historic JasPer mistake.
What is @mdadams's opinion? How was this supposed to work?

2020-08-25 08:22 UTC, MaxKellermann commented
@mdadams please clarify how the JasPer headers were supposed to be used.
Right now, JasPer is broken, and has always been.

2020-08-25 15:16 UTC, mdadams commented
> @mdadams please clarify how the JasPer headers were supposed to be used.
> Right now, JasPer is broken, and has always been.

Users can include individual headers or simply jasper/jasper.h if they like, if thar's what you meant.

2020-08-25 15:26 UTC, MaxKellermann commented
> Users can include individual headers or simply jasper/jasper.h if they like, if thar's what you meant.

No. This is about *how* to include those headers.
`#include <jas_stream.h>` or `#include <jasper/jas_stream.h>`?
`#include <jasper.h>` or `#include <jasper/jasper.h>`?

JasPer is currently broken, and we could easily fix this, but we need to know how the policy is. It is undocumented currently and inconsistent in the example code.

2020-08-25 15:42 UTC, mdadams commented
External  library users should use #include <jasper/SOMEHEADER.h>.
The include directory should be the directory containing the jasper directory not the jasper directory itself.
Is that helpful?

2020-08-25 16:02 UTC, MaxKellermann commented
> External library users should use #include <jasper/SOMEHEADER.h>.

Look at `src/appl/dummy2.c`:
https://github.com/jasper-software/jasper/blob/9aef6d91a82a8a6aecb575cbee57f74470603cc2/src/appl/dummy2.c#L3

> The include directory should be the directory containing the jasper directory not the jasper directory itself.

This is not what JasPer's pkg-config file does:
https://github.com/jasper-software/jasper/blob/9aef6d91a82a8a6aecb575cbee57f74470603cc2/build/jasper.pc.in#L9

This pkg-config file makes it impossible to `#include <jasper/anything>` because it adds `${includedir}/jasper` to the search path, but `${includedir}/jasper/jasper/jasper.h` doesn't exist. And this is the bug this PR attempts to fix, by adding another search path.

Now if `<jasper/*.h>` shall be used, then this PR is wrong and we should have just:
```
Cflags: -I${includedir}
```

2020-08-25 16:17 UTC, MaxKellermann requested changes
This PR adds the correct `-I` flag, but the old one should be removed, because it was wrong.

2020-09-20 18:31 UTC, merged

2020-09-20 18:31 UTC, mdadams commented
The demo jasper applications jasper and jiv are built by the normal CMake build process of JasPer.  Don't the package files only impact users who build code with the library AFTER it has been installed?  I'm sorry but I am not familiar with these files.  The one currently used in JasPer was provided by someone else.  I think that it might have been a package manager for one of the Linux distributions.  In any case, it would seem that this pull request moves things more in the right direction of being correct.  So, I'll merge this PR.  I would be interested in knowing, however, if the other incorrect include directory can be removed from this packaging file.  It should not impact the build process for JasPer as far as I can tell, but maybe I am misunderstanding how this packaging file is used.